export const ADD_PRODUCT = 'ADD_PRODUCT';
export const SUCCESS_ADD_PRODUCT = 'SUCCESS_ADD_PRODUCT';
export const FAILED_ADD_PRODUCT = 'FAILED_ADD_PRODUCT';

export const START_PRODUCTS_DOWNLOAD = 'START_PRODUCTS_DOWNLOAD';
export const SUCCESS_PRODUCTS_DOWNLOAD = 'SUCCESS_PRODUCTS_DOWNLOAD';
export const FAILED_PRODUCTS_DOWNLOAD = 'FAILED_PRODUCTS_DOWNLOAD';

export const GET_PRODUCT_DELETE = 'GET_PRODUCT_DELETE';
export const DELETED_PRODUCT_SUCCESS = 'DELETED_PRODUCT_SUCCESS';
export const DELETED_PRODUCT_FAILED = 'DELETED_PRODUCT_FAILED';

export const GET_PRODUCT_EDIT = 'GET_PRODUCT_EDIT';
export const START_EDIT_PRODUCT = 'START_EDIT_PRODUCT';
export const EDITED_PRODUCT_SUCCESS = 'EDITED_PRODUCT_SUCCESS';
export const EDITED_PRODUCT_FAILED = 'EDITED_PRODUCT_FAILED';
